### PR TITLE
Trying to merge the voice rcv thingy with the main thingy hopefully I dont mess up a thingy

### PR DESCRIPTION
**Pull request by Youareyou64**
### Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)
- [x] None of the above

### CODE REVIEW

**Comment by sairam4123** [comment]
Lol, I made that before you did this.

**Comment by sairam4123** [comment]
https://github.com/sairam4123/no-discord-py-broken

**Comment by sairam4123** [comment]
And well, as I'm blocked by Rapptz, I can't comment in any of the repos he made, so, I'll post the link of the FutureTime here.

**Comment by sairam4123** [comment]
https://github.com/Rapptz/RoboDanny/blob/rewrite/cogs/utils/time.py

**Comment by sairam4123** [comment]
https://github.com/Rapptz/RoboDanny/blob/rewrite/cogs/utils/time.py#L66

**Comment by Youareyou64** [comment]
Ah, that explains why I couldn't @ you in my comment. I ended up using someone else's merged version because I was having trouble, thanks for this though! I'm trying to understand exactly what it does, I see that it is responsible for setting the time for the listening to end, but does an argument (parameter?) need to be passed to it somehow?

**Comment by sairam4123** [comment]
Well, just DM me on Discord Sairam#1724, I'll provide you the latest updated code, and well, mine is not that up-to-date tho.

**Comment by sairam4123** [comment]
Well, can you show the error, because I was having trouble as well, but, that was fixed when, I just had downloaded the binary opus files and just loaded up.

**Pull request merged**
